name: WPCS check

on:
  push:
    branches:
      - '**'

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    name: Fast Woo Order Lookup lint with PHPCS. PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-scripts

    - name: Lint with phpcs
      run: composer phpcs